apiRules:
- include:
    uidRegex: ^MyTested.Mvc.AuthenticationScheme
- include:
    uidRegex: ^MyTested.Mvc.ContentType
- include:
    uidRegex: ^MyTested.Mvc.HttpHeader
- include:
    uidRegex: ^MyTested.Mvc.HttpMethod
- include:
    uidRegex: ^MyTested.Mvc.HttpScheme
- include:
    uidRegex: ^MyTested.Mvc.HttpStatusCode
- include:
    uidRegex: ^MyTested.Mvc.MyMvc
- include:
    uidRegex: ^MyTested.Mvc.ServiceCollectionExtensions
- include:
    uidRegex: ^MyTested.Mvc.With
- exclude:
    type: Class
- exclude:
    uidRegex: IAnd
- exclude:
    uidRegex: ^MyTested.Mvc.Internal
- include:
    type: Interface
